# 1. 环境初始化 (保持不变)
$idfProfile = "D:\Espressif\tools\Microsoft.v5.3.5.PowerShell_profile.ps1"
if (Test-Path $idfProfile) { . $idfProfile } else { Write-Host "Profile Not Found"; pause; exit }

$versions = @("n8r2", "n8r8", "n16r8")
$outputDir = "release_bins"
if (!(Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force }

foreach ($v in $versions) {
    $buildPath = "build_$v"
    $targetBin = "$outputDir/EasyMCU_ESP32S3_$v.bin"

    Write-Host "`n>>> Processing Version: $v <<<" -ForegroundColor Cyan

    if (Test-Path $buildPath) {
        Push-Location $buildPath
        
        if (Test-Path "flash_args") {
            # 1. 提取全局设置
            $content = Get-Content "flash_args" -Raw
            $flashMode = if ($content -match "--flash_mode\s+(\w+)") { $matches[1] } else { "dio" }
            $flashFreq = if ($content -match "--flash_freq\s+(\w+)") { $matches[1] } else { "80m" }
            $flashSize = if ($content -match "--flash_size\s+(\w+)") { $matches[1] } else { "detect" }

            # 2. 拆分地址和文件路径
            $fileList = @()
            Get-Content "flash_args" | ForEach-Object {
                $line = $_.Trim()
                if ($line -and $line -notmatch "^--") {
                    $parts = $line -split "\s+", 2
                    if ($parts.Count -eq 2) {
                        $fileList += $parts[0]
                        $fileList += $parts[1]
                    }
                }
            }

            Write-Host "Merging for ESP32-S3 (Mode: $flashMode, Size: $flashSize)" -ForegroundColor Gray
            
            # 3. 构造参数数组 (排除芯片参数)
            $mergeParams = @(
                "merge_bin",
                "-o", "merged.bin",
                "--flash_mode", $flashMode,
                "--flash_freq", $flashFreq,
                "--flash_size", $flashSize
            )
            $mergeParams += $fileList

            # 4. 显式指定芯片参数并调用，同时确保输出错误信息
            try {
                & esptool.py --chip esp32s3 $mergeParams 2>&1 | Out-String -Stream | Write-Host -ForegroundColor White
            } catch {
                Write-Host "esptool.py crashed!" -ForegroundColor Red
            }

            # 增加一个检查：如果合并失败，确保不会误报
            if (!(Test-Path "merged.bin")) {
                Write-Host "Critical: merged.bin was not generated by esptool.py!" -ForegroundColor Red
            }
        }
        
        Pop-Location

        # 5. 移动并重命名
        if (Test-Path "$buildPath/merged.bin") {
            Move-Item "$buildPath/merged.bin" $targetBin -Force
            Write-Host "Success: $targetBin created." -ForegroundColor Green
        } else {
            Write-Host "Error: Merge failed for $v" -ForegroundColor Red
        }
    } else {
        Write-Host "Skip: $buildPath not found." -ForegroundColor Yellow
    }
}

Write-Host "`n--- All Tasks Finished! ---" -ForegroundColor Yellow
pause